[workspace]
resolver = "3"
members = ["collar", "otr_*", "otrc", "otrrun"]

[workspace.package]
license = "MIT"
readme = "README.md"
edition = "2024"
rust-version = "1.94.0"

[workspace.dependencies]

# External dependencies
colored = "3.1.1"
derive_more = { version = "2.0.1", features = ["full"] }
itertools = "0.14.0"
num = { version = "0.4.3", features = ["num-bigint"] }
serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_cbor = "0.11.2"
toml = "1.0.7"
clap = { version = "4.5.60", features = ["derive"] }



# Workspace members
otr_compiler = { path = "otr_compiler", version = "0.1.0"}
otr_runtime = { path = "otr_runtime", version = "0.1.0"}
otr_core = { path = "otr_core", version = "0.1.0"}
otr_config = { path = "otr_config", version = "0.1.0"}
otr_ffi = { path = "otr_ffi", version = "0.1.0"}